# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c24c566fcdffa82db02848a49fcf6046a6b1d43a9b0e785561785ad8001c0337c85df84e97101e6c4418d83d73d165252de7427ba00a0c6be56de57f065c730

test:
  secret_key_base: 3c41217113a3aa6d3b7097fd41c459d9f6747d2994c7f6b7433db6314438043f7b3ee164f93f359bae30fa745e1827149eaaca58bfad58e28b16ca0a25d1cb7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
